language: ruby
notifications:
  irc: 'irc.freenode.org#padrino'
  recipients:
    - namusyaka@gmail.com
before_install: gem install bundler --pre
install:
  - gem update --system
  - bundle update
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-19mode
  include:
    - rvm: 1.9.3
      gemfile: Gemfile
      services: mongodb

    - rvm: 2.0.0
      gemfile: Gemfile
      services: mongodb

    - rvm: 2.1.0
      gemfile: Gemfile
      services: mongodb

    - rvm: jruby-19mode
      gemfile: Gemfile
      services: mongodb

    - rvm: rbx
      gemfile: Gemfile
      services: mongodb

    - rvm: 1.9.3
      gemfile: gemfiles/activerecord-4.0.gemfile

    - rvm: 2.0.0
      gemfile: gemfiles/activerecord-4.0.gemfile

    - rvm: 2.1.0
      gemfile: gemfiles/activerecord-4.0.gemfile

    - rvm: jruby-19mode
      gemfile: gemfiles/activerecord-4.0.gemfile

    - rvm: rbx
      gemfile: gemfiles/activerecord-4.0.gemfile

    - rvm: 1.9.3
      gemfile: gemfiles/activerecord-4.1.gemfile

    - rvm: 2.0.0
      gemfile: gemfiles/activerecord-4.1.gemfile

    - rvm: 2.1.0
      gemfile: gemfiles/activerecord-4.1.gemfile

    - rvm: jruby-19mode
      gemfile: gemfiles/activerecord-4.1.gemfile

    - rvm: rbx
      gemfile: gemfiles/activerecord-4.1.gemfile
